version: '3.8'

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: SaturnBase
      MYSQL_ROOT_PASSWORD: myrootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - django_network
    healthcheck: 
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: >
      sh -c "echo 'Waiting for MySQL...' && sleep 5 &&
             python /app/SaturnBase/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django_network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - django_network


volumes:
  db_data:

networks:
  django_network:
    driver: bridge
