# Generated by Django 5.1.6 on 2025-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medias', '0002_rename_alt_text_medias_alttext_medias_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
